#!/usr/bin/env python3
"""Build the word banks for Key Terms.

Teachers edit the CSV files in banks/source/ (one per subject).
Run:  python build_banks.py
It checks every row, then writes banks/banks.js and updates the
cache list and version in sw.js so installed copies pick up changes.
Uses the Python standard library only.
"""
import csv, hashlib, json, re, sys, unicodedata
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "banks" / "source"
OUT = ROOT / "banks" / "banks.js"
SW = ROOT / "sw.js"
COLS = ["term", "clue", "image", "topic", "tier", "question",
        "correct_answer", "wrong_1", "wrong_2", "wrong_3", "explanation"]

errors, warnings = [], []

def read_csv(path):
    # utf-8-sig copes with the byte-order mark Excel adds to "CSV UTF-8" files
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))

def follow_up(where, r):
    opts = [r["correct_answer"], r["wrong_1"], r["wrong_2"], r["wrong_3"]]
    missing = [k for k in ("question", "correct_answer", "wrong_1", "wrong_2", "wrong_3", "explanation") if not r[k]]
    if missing:
        errors.append(f"{where}: missing {', '.join(missing)}"); return None
    if len(set(opts)) < 4:  # exact match, so capital-letter distractors are allowed
        errors.append(f"{where}: the four answer options must all be different")
    return {"q": r["question"], "options": opts, "answer": 0, "explain": r["explanation"]}

def check_row(sid, n, row, by_key, items):
    """A term's first row defines it. Later rows with the same term and a
    blank clue add extra follow-up questions, one of which is picked at random."""
    where = f"{sid}.csv row {n}"
    r = {k: (row.get(k) or "").strip() for k in COLS}
    term = r["term"]
    if not term:
        errors.append(f"{where}: missing term"); return
    plain = unicodedata.normalize("NFD", term).encode("ascii", "ignore").decode()
    key = re.sub(r"[^a-z]", "", plain.lower())

    if key in by_key:
        if r["clue"]:
            errors.append(f"{where}: '{term}' already appears in row {by_key[key]['row']}. "
                          "To add another follow-up question, leave the clue blank.")
            return
        fu = follow_up(where, r)
        if fu: by_key[key]["item"]["followups"].append(fu)
        return

    missing = [k for k in ("clue", "topic", "tier") if not r[k]]
    if missing:
        errors.append(f"{where}: first row for '{term}' is missing {', '.join(missing)}"); return
    if re.search(r"[^A-Za-zÀ-ÖØ-öø-ÿ \-]", term):
        errors.append(f"{where}: term '{term}' may only contain letters (accents allowed), spaces and hyphens")
    if not key:
        errors.append(f"{where}: term has no letters")
    if r["tier"].upper() not in ("F", "H"):
        errors.append(f"{where}: tier must be F or H, not '{r['tier']}'")
    if r["image"]:
        if not (ROOT / r["image"]).exists():
            errors.append(f"{where}: image '{r['image']}' not found")
    elif re.search(r"\b" + re.escape(term.lower()) + r"\b", r["clue"].lower()):
        warnings.append(f"{where}: the clue contains the answer '{term}'")
    fu = follow_up(where, r)
    item = {"term": term, "clue": r["clue"], "image": r["image"] or None,
            "topic": r["topic"], "tier": r["tier"].upper(), "followups": [fu] if fu else []}
    by_key[key] = {"row": n, "item": item}
    items.append(item)

def main():
    subjects = read_csv(SRC / "subjects.csv")
    banks = []
    for s in subjects:
        sid = s["id"].strip()
        path = SRC / f"{sid}.csv"
        if not path.exists():
            errors.append(f"subjects.csv lists '{sid}' but {path.name} is missing"); continue
        by_key, items = {}, []
        for n, row in enumerate(read_csv(path), start=2):
            if not any((v or "").strip() for v in row.values()):
                continue  # blank row
            check_row(sid, n, row, by_key, items)
        if len(items) < 10:
            warnings.append(f"{sid}: only {len(items)} terms; sets are 10 long")
        banks.append({"id": sid, "subject": s["subject"].strip(),
                      "department": s["department"].strip(), "items": items})

    for w in warnings: print("WARNING:", w)
    if errors:
        for e in errors: print("ERROR:", e)
        print(f"\n{len(errors)} error(s). Nothing was written. Fix them and run again.")
        sys.exit(1)

    js = "// Generated by build_banks.py from banks/source/*.csv. Don't edit by hand.\n"
    js += "window.BANKS = " + json.dumps(banks, ensure_ascii=False, indent=1) + ";\n"
    OUT.write_text(js, encoding="utf-8")

    # Refresh the service worker's file list and version.
    files = ["./", "./index.html", "./play.html", "./manifest.json", "./banks/banks.js"]
    files += sorted("./" + p.relative_to(ROOT).as_posix() for p in (ROOT / "icons").glob("*.png"))
    files += sorted("./" + p.relative_to(ROOT).as_posix() for p in (ROOT / "images").glob("*.svg"))
    h = hashlib.sha1()
    for f in files:
        p = ROOT / (f[2:] or "index.html")
        if p.is_file(): h.update(p.read_bytes())
    block = (f'const VERSION = "key-terms-{h.hexdigest()[:10]}";\n'
             f"const FILES = {json.dumps(files, indent=2)};\n")
    sw = SW.read_text(encoding="utf-8")
    sw = re.sub(r"// BUILD:START\n.*?// BUILD:END", "// BUILD:START\n" + block + "// BUILD:END", sw, flags=re.S)
    SW.write_text(sw, encoding="utf-8")

    total = sum(len(b["items"]) for b in banks)
    print(f"Built {len(banks)} subjects, {total} terms -> {OUT.relative_to(ROOT)}")
    for b in banks:
        fus = sum(len(i["followups"]) for i in b["items"])
        print(f"  {b['subject']}: {len(b['items'])} terms, {fus} follow-ups ({sum(1 for i in b['items'] if i['image'])} with pictures)")

if __name__ == "__main__":
    main()
